dist: bionic

language: cpp
compiler:
  - clang-7
  - g++-7.4.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake .. -D ENABLE_COVERAGE:BOOL=TRUE
  - cmake --build . -- -j2
  - ctest -j2 --verbose
  - bash <(curl -s https://codecov.io/bash)
