dist: trusty
language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y upgrade

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake-3.18
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- VERBOSE=1
  - ctest --verbose
  - bash <(curl -s https://codecov.io/bash)
