dist: bionic

language: cpp

before_install:
  - sudo apt-get -q update
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install llvm
  - sudo apt-get -y install clang-9.0

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --verbose
  - bash <(curl -s https://codecov.io/bash)
