dist: bionic

language: cpp
compiler:
  - clang-7
  - g++-7.4.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --verbose
