language: cpp
os: osx

jobs:
  include:
  - osx_image: xcode11

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- VERBOSE=1
  - ctest --verbose
  - bash <(curl -s https://codecov.io/bash)
