dist: trusty
language: cpp

compiler:
  - clang
  - gcc

install: make get-deps

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake-3.18
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6
          packages:
            - clang-6
            - cmake-3.18
      env:
        - MATRIX_EVAL="CC=clang-6 && CXX=clang++-6"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- VERBOSE=1
  - ctest --verbose
  - bash <(curl -s https://codecov.io/bash)
